### ISSUE TITLE
"spawn UNKNOWN" error show after cjs-to-es6 User.js on windows 10

### ISSUE THREAD

**Issue by heroghost** [nolanlawson/cjs-to-es6#3]
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1023:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:387:9)
    at spawn (C:\Users\sunzhjie\AppData\Roaming\npm\node_modules\cjs-to-es6\node
_modules\child-process-promise\lib\index.js:81:23)
    at runCodeshift (C:\Users\sunzhjie\AppData\Roaming\npm\node_modules\cjs-to-e
s6\index.js:57:15)
    at derequireify (C:\Users\sunzhjie\AppData\Roaming\npm\node_modules\cjs-to-e
s6\index.js:76:10)
    at C:\Users\sunzhjie\AppData\Roaming\npm\node_modules\cjs-to-es6\index.js:10
5:10

**Comment by abergs** [comment]
Same for me!

**Comment by SwiftPlayer** [comment]
Same for me!

**Comment by awarberg** [comment]
I am getting the same error as @heroghost

**Comment by carlos-** [comment]
+1

**Comment by carlos-** [comment]
The problem is caused by a call to _childProcess.spawn(command, args, options);_ which Windows does not know how to handle .... I tried in a Mac and worked perfectly.

**Comment by altano** [comment]
Just an FYI: I submitted a pull request with Windows support last month (^^ #7) but I don't think @nolanlawson is still monitoring this repo (since there's a pull request from Sept '17 with no comments or activity). ¯\_(ツ)_/¯
